Repository NVIDIA/garak, pull requests merged in 2024-10, with the labels that each got.

#936 reporting: tidy config details, add payload audit info
  garak/analyze/report_digest.py
  garak/analyze/templates/digest_header.jinja
Labels: reporting

#933 payloads: web-related, incl. `probes.encoding` migration
  garak/data/payloads/access_shell_commands.json
  garak/data/payloads/domains_latentinjection.json
  garak/data/payloads/encoded.json
  garak/data/payloads/example_domains_xss.json
  garak/data/payloads/rude_chinese.json
  garak/data/payloads/rude_french.json
  garak/data/payloads/slur_terms_en.json
  garak/data/payloads/text_en.json
  garak/data/payloads/web_html_js.json
  garak/data/typology_payloads.tsv
  garak/payloads.py
  garak/probes/encoding.py
  garak/probes/grandma.py
  garak/probes/latentinjection.py
  garak/probes/xss.py
  tests/test_payloads.py
Labels: enhancement, probes

#945 update: rename `replay` plugins to `divergence`
  docs/source/detectors.rst
  docs/source/garak.detectors.divergence.rst
  docs/source/garak.detectors.replay.rst
  docs/source/garak.probes.divergence.rst
  docs/source/garak.probes.replay.rst
  docs/source/probes.rst
  garak/data/calibration/calibration-2024-09update.json
  garak/detectors/divergence.py
  garak/probes/divergence.py
Labels: enhancement

#947 probe: add whois injection to latentinjection
  garak/cli.py
  garak/data/payloads/whois_injection_contexts.json
  garak/probes/latentinjection.py
  tests/probes/test_probes_latentinjection.py
Labels: probes

#954 architecture: factor HFCompatible out
  garak/buffs/paraphrase.py
  garak/detectors/base.py
  garak/generators/huggingface.py
  garak/resources/api/huggingface.py
  tests/buffs/test_buffs_paraphrase.py
Labels: enhancement

#817 generator: support of azure openai
  docs/source/garak.generators.azure.rst
  docs/source/generators.rst
  garak/generators/azure.py
  tests/generators/openai.json
  tests/generators/test_azure.py
  tests/generators/test_generators.py
Labels: generators

#957 docs: update faq
  FAQ.md
  docs/source/_config.rst
  docs/source/_plugins.rst
  docs/source/basic.rst
  docs/source/buffs.rst
  docs/source/garak.buffs.rst
  garak/buffs/base.py
Labels: documentation

#965 docs: centralise faq
  docs/source/_config.rst
  docs/source/_plugins.rst
  docs/source/attempt.rst
  docs/source/basic.rst
  docs/source/configurable.rst
  docs/source/contributing.rst
  docs/source/how.rst
  docs/source/index.rst
  docs/source/payloads.rst
  docs/source/report.rst
  docs/source/reporting.rst
  docs/source/usage.rst
Labels: documentation

#964 docs: make project scope clear and note that contributors should check it
  CONTRIBUTING.md
  FAQ.md
  README.md
Labels: documentation

#968 docs: clarify "contributing" document
  docs/source/basic.rst
  docs/source/contributing.rst
Labels: documentation

#966 docs: require core config top- and second-level params to be documented
  tests/test_docs.py
Labels: documentation
