Repository NVIDIA/garak, pull requests merged in 2025-05, with the labels that each got.

#1205 update `Tier` impl
  docs/source/extending.probe.rst
  docs/source/garak.probes._tier.rst
  docs/source/probes.rst
  garak/analyze/qual_review.py
  garak/probes/__init__.py
  garak/probes/_tier.py
  garak/probes/ansiescape.py
  garak/probes/atkgen.py
  garak/probes/av_spam_scanning.py
  garak/probes/base.py
  garak/probes/continuation.py
  garak/probes/dan.py
  garak/probes/divergence.py
  garak/probes/donotanswer.py
  garak/probes/encoding.py
  garak/probes/exploitation.py
  garak/probes/fileformats.py
  garak/probes/glitch.py
  garak/probes/goodside.py
  garak/probes/grandma.py
  garak/probes/latentinjection.py
  garak/probes/leakreplay.py
  garak/probes/lmrc.py
  garak/probes/malwaregen.py
  garak/probes/misleading.py
  garak/probes/packagehallucination.py
  garak/probes/phrasing.py
  garak/probes/promptinject.py
  garak/probes/realtoxicityprompts.py
  garak/probes/snowball.py
  garak/probes/suffix.py
  garak/probes/tap.py
  garak/probes/test.py
  garak/probes/topic.py
  garak/probes/visual_jailbreak.py
  garak/probes/xss.py
  tests/probes/test_probes.py
Labels: architecture

#1194 reporting: add option for no group score
  docs/source/configurable.rst
  garak/analyze/report_digest.py
  garak/analyze/templates/digest_group.jinja
  garak/resources/garak.core.yaml
Labels: reporting

#1215 docs: formatting fixes
  docs/source/attempt.rst
  docs/source/configurable.rst
  docs/source/extending.probe.rst
  docs/source/index.rst
  docs/source/langservice.rst
  docs/source/translation.rst
  garak/probes/_tier.py
Labels: documentation

#1218 reporting: aggregate probe as min
  garak/analyze/report_digest.py
  garak/analyze/templates/digest_group.jinja
  garak/analyze/templates/digest_probe.jinja
Labels: reporting

#1216 reporting: add defcon lozenges for relative & absolute scores
  docs/source/index.rst
  docs/source/reporting.rst
  garak/analyze/__init__.py
  garak/analyze/calibration.py
  garak/analyze/qual_review.py
  garak/analyze/report_digest.py
  garak/analyze/templates/digest_detector.jinja
  garak/analyze/templates/digest_header.jinja
  tests/analyze/test_calibration.py
Labels: reporting

#1178 Update/refactor specialwords
  garak/detectors/mitigation.py
  garak/detectors/specialwords.py
  garak/detectors/unsafe_content.py
  garak/probes/grandma.py
  garak/probes/phrasing.py
  garak/resources/fixer/20250423_specialwords.py
Labels: detectors

#1227 update: revert default `_config.run.generations` to `5`
  garak/resources/garak.core.yaml
Labels: architecture

#1226 fix: stop `atkgen` turn count variation in test relying on fixed turn count
  garak/probes/atkgen.py
  tests/langservice/probes/test_probes_base.py
Labels: bug, probes, tests

#1212 reporting: smooth z-score wildness
  garak/analyze/__init__.py
  garak/analyze/calibration.py
  garak/probes/atkgen.py
  tests/langservice/probes/test_probes_base.py
  tests/probes/test_probes_atkgen.py
  tests/test_attempt.py
Labels: reporting

#1229 fix plugin cache tests
  tests/plugins/test_plugin_cache.py
Labels: tests

#1184 ux: move translator load msg into translator instantiation
  docs/source/translation.rst
  garak/harnesses/base.py
  garak/langproviders/base.py
  garak/langservice.py
Labels: cli, ux

#1234 reporting: change default aggregation
  garak/analyze/report_digest.py
  garak/analyze/templates/digest_group.jinja
  garak/analyze/templates/digest_header.jinja
  garak/resources/garak.core.yaml
Labels: reporting
