Repository NVIDIA/garak, pull requests merged in 2025-08, with the labels that each got.

#1252 cohere version upgrade
  garak/generators/cohere.py
  pyproject.toml
  requirements.txt
  tests/generators/test_cohere.py
Labels: generators

#1326 feature: ren failure -> attack success
  garak/evaluators/base.py
Labels: cli, ux

#1259 Added more generalized version of Markdown exfil probe
  garak/data/misp_descriptions.tsv
  garak/data/xss/xss_concat_prompt_templates/basic_concat_inst.txt
  garak/data/xss/xss_domains.txt
  garak/data/xss/xss_encodings.txt
  garak/data/xss/xss_full_uri_prompt_templates/direct.txt
  garak/data/xss/xss_full_uri_prompt_templates/email.txt
  garak/data/xss/xss_injected_actions.txt
  garak/data/xss/xss_injection_markers.txt
  garak/data/xss/xss_link_display_texts.txt
  garak/data/xss/xss_var_names.txt
  garak/detectors/xss.py
  garak/probes/xss.py
  tests/detectors/test_detectors_xss.py
Labels: architecture, probes

#1341 docs: update contact email in readme
  README.md
Labels: documentation

#1348 reporting: update defcon descriptions to talk about risk
  garak/analyze/__init__.py
Labels: reporting
