Repository NVIDIA/garak, pull requests merged in 2025-07, with the labels that each got.

#1180 probe: doctor attack + encoding/Leet
  docs/source/garak.probes.doctor.rst
  docs/source/probes.rst
  garak/probes/doctor.py
  garak/probes/encoding.py
  garak/resources/encodings.py
  tests/probes/test_probes_doctor.py
Labels: probes, new plugin

#1286 documentation: typo fix
  garak/probes/grandma.py
  garak/resources/plugin_cache.json
Labels: documentation

#1308 download models used in translation tests early
  .github/workflows/test_macos.yml
Labels: tests, housekeeping
